apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-ms-invoices
  namespace: cx-ayala-dev
  labels:
    app: cu-ms-invoices
    depto: pagos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu-ms-invoices
  template:
    metadata:
      labels:
        app: cu-ms-invoices
    spec:
      containers:
      - name: hola-mundo
        image: cxayala/cu-ms-invoices:{{ imageTag }}
        ports:
          - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        envFrom:
            - configMapRef:
                name: cu-ms-invoices
            - secretRef:
                name: cu-ms-invoices
        volumeMounts:
            - name: config
              mountPath: /app/config
        startupProbe:
          httpGet:
            path: /startup
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      volumes:
        - name: config
          configMap:
            name: cu-ms-invoices-config
---
apiVersion: v1
kind: Service
metadata:
  name: cu-ms-invoices-svc
  namespace: cx-ayala-dev
spec:
  selector:
    app: cu-ms-invoices
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cu-ms-invoices
  namespace: cx-ayala-dev
data:
  LOG_LEVEL: debug
  DATABASE_HOST: "mi-postgres-postgresql-primary.cx-ayala-dev.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cu-ms-invoices-config
  namespace: cx-ayala-dev
data:
  app.conf: |
    server {
      port 1000
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cu-ms-invoices
  namespace: cx-ayala-dev
data:
  DATABASE_PASSWORD: TWlQYXNzd29yZFNlZ3VybzEyMw==
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cu-ms-invoices
  namespace: cx-ayala-dev
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: cu-ms-invoices
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization ##en base a porcentaje de uso
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---